#!/home/httpd/musicbrainz/mb_server/cgi-bin/perl -w
# vi: set ts=4 sw=4 :
#____________________________________________________________________________
#
#   MusicBrainz -- the open internet music database
#
#   Copyright (C) 2004 Robert Kaye
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   $Id$
#____________________________________________________________________________

no warnings qw( portable );
use strict;
use Apache;
use Apache::Request;
use Apache::Constants qw( BAD_REQUEST );
use MetaBrainz::Server::Defs;
use MetaBrainz::Server::MetaBrainz;
use Sql;

my $mb = new MetaBrainz::Server::MetaBrainz(1);
$mb->Login();
my $sql =  Sql->new($mb->{DBH});

my $r = Apache->request();
my %args; { no warnings; %args = $r->args };
my $out = "";

if (exists $args{moderator} )
{
    my $days_per_dollar = "18.25";

    $out = $sql->SelectSingleValue("SELECT ((extract(epoch from now()) - extract(epoch from payment_date)) / 86400) > ((amount + fee) * $days_per_dollar) as nag
                                           FROM donation 
                                          WHERE moderator = ? 
                                       ORDER BY payment_date DESC 
                                          LIMIT 1", $args{moderator});

    $out = "-1" if ($out eq '');
    $out .= "\n";
    $r->status(200);
}
else
{
    $r->status(BAD_REQUEST);
}

$r->content_type("text/plain");
$r->header_out('Content-Length', length($out));
$r->send_http_header();

print $out
